/*DATAMIGRATION 859C49F1-F32E-412A-AFC4-98FE090CD27D*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'GostInfo';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'GostInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'GostInfo', 'OIB', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'GostInfo', 'BrojMobilnogTelefona', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'GostInfo', 'AdresaID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Informacije', 'GostInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Informacije', 'GostInfo', 'OIB', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Informacije', 'GostInfo', 'BrojMobilnogTelefona', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Informacije', 'GostInfo', 'AdresaID', 'uniqueidentifier';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...

INSERT INTO _Informacije.GostInfo(ID, OIB, BrojMobilnogTelefona, AdresaID)
SELECT x.ID, x.OIB, x.BrojMobilnogTelefona, x.AdresaID
FROM 
	_Hoteli.GostInfo x
	LEFT JOIN _Informacije.GostInfo existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Informacije', 'GostInfo', 'ID, OIB, BrojMobilnogTelefona, AdresaID';
