/*DATAMIGRATION 8BC9ADCD-0251-419E-ACF6-599D787B394C*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'OpcenitoInfo';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'OpcenitoInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'OpcenitoInfo', 'BrojTelefona', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'OpcenitoInfo', 'Email', 'nvarchar(256)';

EXEC Rhetos.DataMigrationUse 'Informacije', 'OpcenitoInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Informacije', 'OpcenitoInfo', 'BrojTelefona', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Informacije', 'OpcenitoInfo', 'Email', 'nvarchar(256)';
GO


INSERT INTO _Informacije.OpcenitoInfo(ID, BrojTelefona, Email)
SELECT x.ID, x.BrojTelefona, x.Email
FROM 
	_Hoteli.OpcenitoInfo x
	LEFT JOIN _Informacije.OpcenitoInfo existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Informacije', 'OpcenitoInfo', 'ID, BrojTelefona, Email';

