/*DATAMIGRATION F4A74A0D-7D1D-49F5-9A64-5DEAD1D41E0B*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'AdresaHotela';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'AdresaHotela', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'AdresaHotela', 'GeocoordinateID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Adrese', 'AdresaHotela', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'AdresaHotela', 'GeocoordinateID', 'uniqueidentifier';
GO

INSERT INTO _Adrese.AdresaHotela(ID, GeocoordinateID)
SELECT x.ID, x.GeocoordinateID
FROM 
	_Hoteli.AdresaHotela x
	LEFT JOIN _Adrese.AdresaHotela existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'Adrese', 'AdresaHotela', 'ID, GeocoordinateID';

	











