/*DATAMIGRATION A3F07400-5208-437F-A136-E503DCAB7B8A*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Drzava';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Drzava', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Drzava', 'ImeDrzave', 'nvarchar(256)';

EXEC Rhetos.DataMigrationUse 'Adrese', 'Drzava', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Drzava', 'ImeDrzave', 'nvarchar(256)';
GO

INSERT INTO _Adrese.Drzava(ID, ImeDrzave)
SELECT x.ID, x.ImeDrzave
FROM 
	_Hoteli.Drzava x
	LEFT JOIN _Adrese.Drzava existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Adrese', 'Drzava', 'ID, ImeDrzave';







