/*DATAMIGRATION 485A15C8-4145-42BE-9728-65B46C6C32C3*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Soba';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'BrojSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'NazivSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'Taksa', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'Slobodna', 'bit';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'HotelID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Soba', 'TipSobeID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'BrojSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'NazivSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'Taksa', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'Slobodna', 'bit';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'HotelID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Sobe', 'Soba', 'TipSobeID', 'uniqueidentifier';
GO

INSERT INTO _Sobe.Soba(ID, BrojSobe, NazivSobe, Taksa, Slobodna, HotelID, TipSobeID)
SELECT x.ID, x.BrojSobe, x.NazivSobe, x.Taksa, x.Slobodna, x.HotelID, x.TipSobeID
FROM 
	_Hoteli.Soba x
	LEFT JOIN _Sobe.Soba existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'Sobe', 'Soba', 'ID, BrojSobe, NazivSobe, Taksa, Slobodna, HotelID, TipSobeID';

	






