/*DATAMIGRATION D516844A-60A0-44C6-8A71-CD10314EE7D9*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Racun';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'Broj', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'DatumIzdavanja', 'date';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'BrojDana', 'int';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'Popust', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'Iznos', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'GostID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Racun', 'HotelID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'Broj', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'DatumIzdavanja', 'date';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'BrojDana', 'int';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'Popust', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'Iznos', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'GostID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Racuni', 'Racun', 'HotelID', 'uniqueidentifier';
GO

INSERT INTO _Racuni.Racun(ID, Broj, DatumIzdavanja, BrojDana, Popust, Iznos, GostID, HotelID)
SELECT x.ID, x.Broj, x.DatumIzdavanja, x.BrojDana, x.Popust, x.Iznos, x.GostID, x.HotelID
FROM 
	_Hoteli.Racun x
	LEFT JOIN _Racuni.Racun existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'Racuni', 'Racun', 'ID, Broj, DatumIzdavanja, BrojDana, Popust, Iznos, GostID, HotelID';








	






