/*DATAMIGRATION 9B3535C1-0A0C-4431-BACC-58A2B21A4C5F*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Geocoordinate';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Geocoordinate', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Geocoordinate', 'Latitude', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Geocoordinate', 'Longitude', 'nvarchar(256)';

EXEC Rhetos.DataMigrationUse 'Adrese', 'Geocoordinate', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Geocoordinate', 'Latitude', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Geocoordinate', 'Longitude', 'nvarchar(256)';
GO

INSERT INTO _Adrese.Geocoordinate(ID, Latitude, Longitude)
SELECT x.ID, x.Latitude, x.Longitude
FROM 
	_Hoteli.Geocoordinate x
	LEFT JOIN _Adrese.Geocoordinate existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Adrese', 'Geocoordinate', 'ID, Latitude, Longitude';







