/*DATAMIGRATION 0DA26249-FB54-4FBC-8E59-CD311210F740*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'SadrzajSobeMap';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobeMap', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobeMap', 'SobaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobeMap', 'SadrzajSobeID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobeMap', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobeMap', 'SobaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobeMap', 'SadrzajSobeID', 'uniqueidentifier';
GO

INSERT INTO _Sobe.SadrzajSobeMap(ID, SobaID, SadrzajSobeID)
SELECT x.ID, x.SobaID, x.SadrzajSobeID
FROM 
	_Hoteli.SadrzajSobeMap x
	LEFT JOIN _Sobe.SadrzajSobeMap existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'Sobe', 'SadrzajSobeMap', 'ID, SobaID, SadrzajSobeID';



	






