/*DATAMIGRATION 4F7A4002-E62E-4BFC-A470-9D2536ED0DBE*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'SadrzajSobe';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobe', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobe', 'OpisSadrzajaSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'SadrzajSobe', 'NadoplataSadrzaja', 'decimal(28, 10)';

EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobe', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobe', 'OpisSadrzajaSobe', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Sobe', 'SadrzajSobe', 'NadoplataSadrzaja', 'decimal(28, 10)';
GO

INSERT INTO _Sobe.SadrzajSobe(ID, OpisSadrzajaSobe, NadoplataSadrzaja)
SELECT x.ID, x.OpisSadrzajaSobe, x.NadoplataSadrzaja
FROM 
	_Hoteli.SadrzajSobe x
	LEFT JOIN _Sobe.SadrzajSobe existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'Sobe', 'SadrzajSobe', 'ID, OpisSadrzajaSobe, NadoplataSadrzaja';



	






