/*DATAMIGRATION 1C7CAC51-596B-4F42-859E-24E4ADA600E0*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Gost';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'Ime', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'Prezime', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'JacinaPrijateljstvaSaGazdom', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'BrojSobeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'GostInfoID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Gost', 'DatumRodjenja', 'date';

EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'Ime', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'Prezime', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'JacinaPrijateljstvaSaGazdom', 'decimal(28, 10)';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'BrojSobeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'GostInfoID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Gosti', 'Gost', 'DatumRodjenja', 'date';
GO

INSERT INTO _Gosti.Gost(ID, Ime, Prezime, JacinaPrijateljstvaSaGazdom, BrojSobeID, GostInfoID, DatumRodjenja)
SELECT x.ID, x.Ime, x.Prezime, x.JacinaPrijateljstvaSaGazdom, x.BrojSobeID, x.GostInfoID, x.DatumRodjenja
FROM 
	_Hoteli.Gost x
	LEFT JOIN _Gosti.Gost existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Gosti', 'Gost', 'ID, Ime, Prezime, JacinaPrijateljstvaSaGazdom, BrojSobeID, GostInfoID, DatumRodjenja';



