/*DATAMIGRATION 5985DED6-1161-4876-87D1-36A3654419FC*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'HotelInfo';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'HotelInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'HotelInfo', 'BrojFaxa', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'HotelInfo', 'Web', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'HotelInfo', 'AdresaID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Informacije', 'HotelInfo', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Informacije', 'HotelInfo', 'BrojFaxa', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Informacije', 'HotelInfo', 'Web', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Informacije', 'HotelInfo', 'AdresaID', 'uniqueidentifier';
GO

INSERT INTO _Informacije.HotelInfo(ID, BrojFaxa, Web, AdresaID)
SELECT x.ID, x.BrojFaxa, x.Web, x.AdresaID
FROM 
	_Hoteli.HotelInfo x
	LEFT JOIN _Informacije.HotelInfo existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Informacije', 'HotelInfo', 'ID, BrojFaxa, Web, AdresaID';
