/*DATAMIGRATION 50CF6298-711A-4DC9-9BCA-0D6E9991206A*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Adresa';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'Ulica', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'KucniBroj', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'DrzavaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'ZupanijaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Adresa', 'GradID', 'uniqueidentifier';

EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'Ulica', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'KucniBroj', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'DrzavaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'ZupanijaID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Adresa', 'GradID', 'uniqueidentifier';
GO

INSERT INTO _Adrese.Adresa(ID, Ulica, KucniBroj, DrzavaID, ZupanijaID, GradID)
SELECT x.ID, x.Ulica, x.KucniBroj, x.DrzavaID, x.ZupanijaID, x.GradID
FROM 
	_Hoteli.Adresa x
	LEFT JOIN _Adrese.Adresa existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Adrese', 'Adresa', 'ID, Ulica, KucniBroj, DrzavaID, ZupanijaID, GradID';





