/*DATAMIGRATION 10985A20-76CA-4E2D-9F1D-4B3A04BBBF33*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Hoteli', 'Grad';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Grad', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Grad', 'ImeGrada', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Hoteli', 'Grad', 'PostanskiBroj', 'nvarchar(256)';

EXEC Rhetos.DataMigrationUse 'Adrese', 'Grad', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Grad', 'ImeGrada', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Adrese', 'Grad', 'PostanskiBroj', 'nvarchar(256)';
GO

INSERT INTO _Adrese.Grad(ID, ImeGrada, PostanskiBroj)
SELECT x.ID, x.ImeGrada, x.PostanskiBroj
FROM 
	_Hoteli.Grad x
	LEFT JOIN _Adrese.Grad existing ON existing.ID = x.ID
WHERE 
	existing.ID IS NULL	

EXEC Rhetos.DataMigrationApplyMultiple 'Adrese', 'Grad', 'ID, ImeGrada, PostanskiBroj';










